# Generated by Django 4.0.4 on 2022-05-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_project_options_alter_project_owner_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanban.row'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
